---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 741309830460264452-QIaP7q7NDizP4shwMMlIhEH4XDNCIlv
:access_token_secret: 8yxHCCCzbkKTjgaDm5f5be5ZnFcYYLA8bLpmyxaawq0Yz
